theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins

title: [Marcela Ribeiro]
description: [Currículo profissional]

logo: [https://raw.githubusercontent.com/Marcela-Rib/Marcela-Rib.github.io/master/Marcela%20Ribeiro.svg]
show_downloads: ["true"]
google_analytics: [Your Google Analytics tracking ID]
