theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins

title: [Marcela Ribeiro]
description: [Currículo profissional]

logo: /assets/Marcela Ribeiro.svg
show_downloads: ["true"]
google_analytics: [Your Google Analytics tracking ID]
